### ISSUE TITLE
AEIP-2 : Property dictionary

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/aeip#13]
### Is your feature request related to a problem?

Actually, the definition of properties inside a token is free.

### Describe the solution you'd like

I suggest to share a property dictionary to define some specific properties to facilitate the interoperability between DApps.

### Additional context

In the wallet app, i manage for the moment inside a property of an NFT:
- "name": the creator can specify a name 
- "description": the creator can specify a description to promote or define his token
- "file": contains in base 64 the file attached in the NFT (image, pdf, etc...)
- "type/mime": contains the type/mime from IANA Database

**Comment by samuelmanzanera** [comment]
Linked to #4

**Comment by pvalette** [comment]
May be, instead of ‘file’, preferable to use ‘content’, ‘body’,… ‘file’ is more associated to a file name, external link.

An image can be huge. For displaying it in a dapp, the GET should not return the complete content due to performance issue. 
The original file is in general stored via an external link (IPFS, in another transaction…).  
-> additional link in the structure 
So the content should be a small image only for displaying purpose.

For image, other parameters can be interested such as the resolution etc…
It is the same for sound files,…

Can be interesting to work also on properties based on the file type.
