### ISSUE TITLE
AEIP-2. Defined Metadata

### ISSUE THREAD

**Issue by pvalette** [archethic-foundation/aeip#4]
### Is your feature request related to a problem?

In order to insure the operability, additional metadata must be described to avoid that people use different terms for same item
Need also to indicate what's required or not, limit etc..

### Describe the solution you'd like

For example:

> In addition of the Name it will be nice to have a dedicated attribute for a short name/code (should be required)
> Not required attributes such as
- Author
- Description
> For Token, need a specific the number of decimals (should be managed by the blockchain during  transfer)

>Images for Tokens must be named  with the size etc.. in order to facilitate the representation of the token in Dapp

If you think that this proposal is interesting, I can work on a more detailed description.  let me know

**Comment by samuel-uniris** [comment]
About the decimals, if you look at the usage in Ethereum smart contracts, most of the tokens are defined with 18 decimals, which only serves the purpose of display of the amount. (Ethereum smart contract only deals with big number). And final it's rare to find some token where the decimals is not 18. You should have very specific reason to not use 18 decimals. It's for this reason we thought to make this complexity in the token definition.

For the image size, names symbol, the token definition provides some arbitrary properties which can be defined in order to extend a token. Some tokens would have image and other not, so this metadata extension - about file - should be optional.
The difficulty is that Archethic tokens can be fungible or non-fungible.
But a client application could determine the type of the token and could try to fetch an "image" property.

We could even approach this by using a JSON schema w/o JSON-LD  to help the identification and validation of the properties for a given definition.

**Comment by Neylix** [comment]
Hello @pvalette 
The AEIP2 aims to be the most general possible because as it is the first implementation of the token standard, we must be flexible to easily update this standard or complete it with new feature or rules.

So in order to add metadata or specific properties as you mentioned, I think the good way is to create a new AEIP which is base on AEIP2 but define specific properties for a specific use case.

So the developer will be able to use specific token standard for some use case or use their own properties if they need or if they can't use the specific token standard.

If you want, I invite you to create a new AEIP based on AEIP2 with specific metadata / properties

Thanks !

**Comment by pvalette** [comment]
**Images**
My concern was not about the image of a Art NFT, but more for _Fungible Token/Coins_
Each wallet, DApp has to map the address of a contract with a bitmap/icon stored locally or in Github, and copied from somewhere. 
The owner of the Coins has no control on this graphical representation, in term of Marketing it is really not the best practice.

By having dedicated fields (and mandatory) for these fields, Archethic can be a diffrentiator as you solve 
- the issue of owner (be sure that all icons are similar, possibility to update the icon)
- facilitate the job of DApp developers as they have not to browse Git to find the logo or to display like ledger a Fake Icon. 

Based on Mobile Development, need to see if a SVG image or bitmap with different sizes.

Concerning Art NFT, a reduced image can be put inside these dedicated image fields, NFT like a document, the owner can put an icon too for representing the file etc..

**Comment by pvalette** [comment]
Hello @Neylix 

Yes if you want to invite me on the Git. I can make some proposals

Best Regards
Philippe

**Comment by samuel-uniris** [comment]
> Thanks for your replies, a few comments
> 
> **About the decimals, if you look at the usage in Ethereum smart contracts, most of the tokens are defined with 18 decimals** Here is a few use cases of Standard Token
> 
> * **Coins**
>   It is true that most of ERC20 tokens have 18 decimals but a few in the TOP 20 have another value (TUSD=6, USDC=6, Celsius=4, ...).  If someone develops a bridge it will be difficult to manage these type of tokens and maintain 100% parity. So, it is necessary to have a backward compatibility with former blockchains (ETH) or others.
> * **Fungible Token**
>   For an use case such as escrow account, we map one-one a Token with EUR/USD, in this case we must have a decimal = 2.
> * **Asset**
>   Another use case that need to manage, it is the tokenization of a asset (Boat for example). In this case the asset is split in X parts (=>supply).  A part is undivided, so the decimal must be 0.
> 
> It is very nice to have a native Token transfer in Archtethic but in comparison other BK, you have no control (or didn't found). For example, in the last Use Case, another DApp/Wallet can split the part in several parts and break the Initial Business Rules
> 
> So it is fundamental (if no other way), to have the decimals field & control, however, the attribute can be optional. (default equals to 18).

I can understand your point of view.

For the decimals parts, it's still subject to discussion even internally 18 decimals is still hard to grasp as for financial operations this is better than float precision. We might add optional "decimals". The main difference in terms of implementation would be during the minting (integration of the decimals in the UTXO's amount) and on the explorer. The latter is not efficient and costly just for UI will require more request to find the decimals and display the right amount.

For the "Asset" case, this is a perfect use case of NFT with collection, where each element of the collection is a part.

For the image use case, we could define another AEIP to specify metadata, hence creating composition / implementations supported by a token.

**Comment by samuelmanzanera** [comment]
Decimals have been done #14

**Comment by pvalette** [comment]
Thanks to have take in account the ‘decimal’ request.

**Comment by samuelmanzanera** [comment]
The definition of required vs template/schema would be part of another AEIP.
Because https://github.com/archethic-foundation/archethic-node/pull/580 implements the decimals description, I close this issue.
